modLoader="javafml" #mandatory
loaderVersion="[31,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
[[mods]] #mandatory
modId="flycommand" #mandatory
version="2.1" #mandatory
displayName="FlyCommandMod" #mandatory
updateJSONURL="https://raw.githubusercontent.com/hamusuke0323/FlyCommandMod/main/update.json" #optional
displayURL="https://www.curseforge.com/minecraft/mc-mods/flycommandmod" #optional
credits="Thanks for downloading this Mod!" #optional
authors="hamusuke2303" #optional
logoFile="icon.png"
description='''
add /fly command.
'''
[[dependencies.examplemod]] #optional
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[31,)" #mandatory
    ordering="NONE"
    side="BOTH"
[[dependencies.examplemod]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2]"
    ordering="NONE"
    side="BOTH"
